### ISSUE TITLE
How to create UUIDs from timestamps?

### ISSUE THREAD

**Issue by cellis** [kripod/uuidv7#5]
There's a postgres lib that allows this: https://github.com/fboulnois/pg_uuidv7, but I'm not sure how to accomplish time to uuidv7 using your library.

**Comment by kripod** [comment]
This isn’t possible, as the library was intentionally kept as simple as possible.

Also, by adding such functionality, the ordering of generated IDs wouldn’t be guaranteed through the `seq` variable over here:

https://github.com/kripod/uuidv7/blob/5cdf6b02d70f07ed506f2ae930601de3f1036a68/src/_common.ts#L11-L17

If you want your proposal to be implemented, please feel free to fork this project, so that it could accept a custom `timestamp`.
